version: "2017-09-20"
pipeline:
  - id: test
    type: script
    vm_config:
      type: linux
      size: extra_large
      image: cdp-runtime/jdk11
    commands:
      - desc: Checkstyle
        cmd: |
          ./gradlew checkstyle --stacktrace
      - desc: Test
        cmd: |
          ./gradlew test --stacktrace
  - id: acceptance-test
    type: script
    vm_config:
      type: linux
      size: extra_large
      image: cdp-runtime/jdk11
    commands:
      - desc: Install dependencies
        cmd: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          echo '04216d65ce0cd3c27223eab035abfeb20a8bef20259398e3b9d9aa8de633286d */usr/local/bin/docker-compose' | sha256sum -c
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - desc: Acceptance Test
        cmd: |
          ./gradlew fullAcceptanceTest --stacktrace
  - id: build-push
    type: script
    vm_config:
      type: linux
      size: extra_large
      image: cdp-runtime/jdk11
    commands:
      - desc: Build and push to repo
        cmd: |
          ./gradlew clean app:bootJar
          IMAGE="container-registry-test.zalando.net/aruha/nakadi-oss:${CDP_BUILD_VERSION}"
          if [ "$CDP_PULL_REQUEST_NUMBER" ]; then
            IMAGE="container-registry-test.zalando.net/aruha/nakadi-oss-pr:${CDP_BUILD_VERSION}"
          fi

          docker buildx create \
                --config /etc/cdp-buildkitd.toml \
                --driver-opt network=host \
                --name cdpbuildx \
                --bootstrap \
                --use

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${IMAGE} \
            --push .
