SET ROLE zalando_nakadi_data_owner;

DROP INDEX subscription_s_subscription_object_idx;
DROP INDEX subscription_expr_expr1_expr2_idx;

ALTER TABLE zn_data.subscription ADD CONSTRAINT subscription_key_fields_hash_is_unique UNIQUE (s_key_fields_hash);