link-google-style: google-style
	@ln -s google_checks.xml checkstyle.xml


google-style: google_checks.xml
	@curl -sO https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml


eclipse-java-google-style: eclipse-java-google-style.xml
	@curl -sO https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml


