FROM registry.opensource.zalan.do/stups/openjdk:8u91-b14-1-22

ENV KAFKA_VERSION="0.8.2.1" SCALA_VERSION="2.10"
ENV KAFKA_IMG="kafka_${SCALA_VERSION}-${KAFKA_VERSION}"
ENV KAFKA_DIR="/opt/${KAFKA_IMG}"

# the script is used here to make it possible to use the same script in travis-ci.org
ADD install-local-kafka.sh /
RUN bash /install-local-kafka.sh
RUN rm /install-local-kafka.sh

WORKDIR ${KAFKA_DIR}

ADD start-local-kafka.sh ${KAFKA_DIR}/

ENTRYPOINT bash start-local-kafka.sh

EXPOSE 9092
